name: CI Build
     
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
 
jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 7.0.x
    - name: Install dependencies
      run: dotnet restore Chorn.AiPullRequestAssistor\Chorn.AiPullRequestAssistor.csproj
    - name: Build windows
      run: dotnet build --framework net7.0 --configuration Release --no-restore Chorn.AiPullRequestAssistor\Chorn.AiPullRequestAssistor.csproj
    - name: Package windows
      run: dotnet publish --framework net7.0 --no-restore --no-build --configuration Release --verbosity normal -o Release/win-x64 Chorn.AiPullRequestAssistor\Chorn.AiPullRequestAssistor.csproj
    - name: Package linux
      run: dotnet publish --framework net7.0 --no-restore --no-build --configuration Release --verbosity normal -o Release/linux-x64 Chorn.AiPullRequestAssistor\Chorn.AiPullRequestAssistor.csproj
    - name: Upload Build Artifact windows
      uses: actions/upload-artifact@v3
      with:
        name: AiPullRequestAssistor-net7-winx64
        path: Release/win-x64
    - name: Upload Build Artifact linux
      uses: actions/upload-artifact@v3
      with:
        name: AiPullRequestAssistor-net7-linuxx64
        path: Release/linux-x64
